[package]
name = "fidget-rhai"
version = "0.4.0"
edition = "2024"
license = "MPL-2.0"
repository = "https://github.com/mkeeter/fidget"
description = "Rhai script evaluation for complex closed-form implicit surfaces"
authors = ["Matt Keeter <matt.j.keeter@gmail.com"]
readme = "../README.md"
rust-version = "1.87"

[dependencies]
fidget-core = { path = "../fidget-core", version = "=0.4.0" }

enum-map.workspace = true
facet.workspace = true
rhai.workspace = true
strum.workspace = true
heck.workspace = true
