name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test-native:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Check
      run: cargo check --all-targets --verbose
    - name: Build
      run: cargo build --verbose --package fidget
    - name: Run tests
      run: cargo test --verbose --package fidget
