name: Check wasm build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-wasm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install wasm target
      run: rustup target add wasm32-unknown-unknown
    - name: Check
      run: cargo check --target=wasm32-unknown-unknown -pfidget --no-default-features --features="rhai,render,mesh"
