name: wasm-demo build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./demos/web-editor/web
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Install wasm target
      run: rustup target add wasm32-unknown-unknown
    - name: Install wasm-pack
      run: |
        curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Install npm dependencies
      run: npm install
    - name: Check Prettier
      run: npx prettier . --check
    - name: Build wasm-demo
      run: npm run build
